project:
  type: website

execute:
  freeze: auto

website:
  title: "Adrián Cidre"
  site-url: "https://cidree.github.io/blog/"
  search: false
  navbar:
    #logo: figures/logo.png
    background: "#2D4156"
    collapse-below: lg
    right:
      - text: Home
        href: index.qmd
      - text: Posts
        href: projects.qmd
      - text: Courses
        href: courses.qmd
      - about.qmd
      - icon: github
        href: https://github.com/Cidree
      - icon: linkedin
        href: https://www.linkedin.com/in/adrian-cidre-gonz%C3%A1lez-8a50371b0/
      - icon: envelope-at
        href: mailto:adrian.cidre@gmail.com
        
  page-footer:
    center: |
      [Contact Adrián Cidre](mailto:adrian.cidre@gmail.com)
    left: |
      Made with [Quarto](https://quarto.org/)
    right: |
      [Github Code Repo](https://github.com/Cidree/blog)
    background: "#2D4156"
    foreground: white
  
  google-analytics:
    tracking-id: "G-J58431JK0F"
    anonymize-ip: true
  cookie-consent:
    style: interstitial
    palette: light

format:
  html:
    theme: 
      light: [lux, 00_styles/quarto_theme.scss]
    css: 00_styles/styles.css
    code-link: true
    code-block-border-left: true
    linkcolor: '#ff0000'
    fontsize: 100%
    mainfont: "Inter"
    monofont: "Fira Code"
    highlight-style: nord
editor: visual

