project:
  type: website

website:
  title: ""
  site-url: "https://www.quarto.org"
  navbar:
    logo: figures/logo.png
    collapse-below: lg
    left:
      - text: Home
        href: index.qmd
      - text: News
        href: projects.qmd
      - text: Courses
        href: courses.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Cidree
      - icon: linkedin
        href: https://www.linkedin.com/in/adrian-cidre-gonz%C3%A1lez-8a50371b0/
      - icon: envelope-at
        href: mailto:adrian.cidre@gmail.com
  page-footer:
    center: |
      [Contact Adrián Cidre](mailto:adrian.cidre@gmail.com)
    left: |
      Made with [Quarto](https://quarto.org/)
    right: |
      [Github Code Repo](https://github.com/Cidree/cidre)
    background: black
    foreground: white
format:
  html:
    theme: 
      light: lux
      dark: [lux, theme_dark_custom.scss]
    css: styles.css
    code-link: true
    code-block-border-left: true
    linkcolor: '#ff0000'
editor: visual

