project:
  type: website

execute:
  freeze: auto

website:
  title: "Adrián Cidre"
  site-url: "https://adrian-cidre.com"
  description: "A blog with R content"
  search:
    location: navbar
    type: overlay
    show-item-context: tree
  navbar:
    #logo: assets/figures/logo.png
    background: "#2D4156"
    collapse-below: lg
    left:
      - text: About
        icon: person-circle
        href: index.qmd
      # - text: Posts
      #   href: posts.qmd
      - text: Courses
        icon: mortarboard-fill
        href: courses.qmd
    right:
      - icon: github
        href: https://github.com/Cidree
      - icon: linkedin
        href: https://www.linkedin.com/in/adrian-cidre-gonz%C3%A1lez-8a50371b0/
      - icon: youtube
        href: https://www.youtube.com/@CidreRForest
      - icon: envelope-at
        href: mailto:adrian.cidre@gmail.com
      - text: "{{< iconify simple-icons kofi >}}"
        href: https://buymeacoffee.com/adriancidre
  page-footer:
    center: |
      [Contact Adrián Cidre](mailto:adrian.cidre@gmail.com)
    left: |
      Made with [Quarto](https://quarto.org/)
    right: |
      [Github Code Repo](https://github.com/Cidree/blog)
    background: "#2D4156"
    foreground: white
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Warning** - This site is under development. Some features may not work as expected."
    type: warning
    position: below-navbar
  
  google-analytics:
    tracking-id: "G-J58431JK0F"
    anonymize-ip: true
  cookie-consent:
    style: interstitial
    palette: light

format:
  html:
    theme: 
      light: [sandstone, assets/styles/custom_theme.scss]
    # css: assets/styles/styles.css
    code-link: true
    code-block-border-left: true
    fontsize: 100%
    highlight-style: arrow

